# Generated by Django 6.0.1 on 2026-03-17 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría (Ej: Serie A, Femenino)')),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='configuracion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='horariocancha',
            options={'ordering': ['hora_inicio']},
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='puede_fichar',
        ),
        migrations.AddField(
            model_name='detallepartido',
            name='equipo_incidencia',
            field=models.ForeignKey(blank=True, help_text='Asegura que los goles no se fuguen si se traspasa al jugador', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='cupos_pagados',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de Jugadores Pagados/Habilitados'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sancionado_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Equipo en Lista Negra hasta:'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='sancionado_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Jugador Suspendido hasta:'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sancionado_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Suspendido (Lista Negra) hasta:'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='cobro_por_jugador',
            field=models.BooleanField(default=False, verbose_name='¿Cobrar inscripción POR JUGADOR en vez de equipo?'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='costo_inscripcion_jugador',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo x Jugador'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fase1_ida_vuelta',
            field=models.BooleanField(default=False, verbose_name='Fase 1 (Todos contra Todos) - Ida y Vuelta'),
        ),
        migrations.AlterField(
            model_name='horariocancha',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo del Turno'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='etapa',
            field=models.CharField(choices=[('F1', 'Fase 1'), ('F2', 'Fase 2'), ('4TOS', 'Cuartos de Final'), ('SEMI', 'Semifinal'), ('TERC', 'Tercer Lugar'), ('FINAL', 'Final')], default='F1', max_length=5),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='costo_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo x Equipo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fase2_ida_vuelta',
            field=models.BooleanField(default=False, verbose_name='Fase 2 (Grupos) - Ida y Vuelta Acumulativa'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fase3_ida_vuelta',
            field=models.BooleanField(default=False, verbose_name='Fase 3 (Eliminatorias/Cuartos) - Ida y Vuelta'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='core.categoria'),
        ),
    ]
