# Generated by Django 6.0.1 on 2026-03-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_alter_configuracion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='grupo_fase2',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
