# Generated by Django 6.0.1 on 2026-03-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_equipo_grupo_fase2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='fase1_ida_vuelta',
            field=models.BooleanField(default=False, verbose_name='Fase 1 (Todos contra Todos) - Ida o Vuelta'),
        ),
    ]
