# Generated by Django 6.0.1 on 2026-03-18 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_torneo_fase1_ida_vuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria', verbose_name='Categoría'),
        ),
    ]
