# Generated by Django 6.0.1 on 2026-03-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_torneo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='categoria',
        ),
    ]
