# Generated by Django 6.0.1 on 2026-03-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_torneo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='categoria',
        ),
    ]
