# Generated by Django 6.0.1 on 2026-03-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_equipo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria', verbose_name='Categoría'),
        ),
    ]
