# Generated by Django 6.0.1 on 2026-03-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_torneo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='inscripciones_abiertas',
            field=models.BooleanField(default=True),
        ),
    ]
