# Generated by Django 6.0.1 on 2026-03-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_torneo_inscripciones_abiertas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='inscripciones_abiertas',
        ),
    ]
