# Generated by Django 6.0.1 on 2026-03-18 15:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_torneo_inscripciones_abiertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='cedula',
            field=models.CharField(max_length=15, validators=[core.models.validar_cedula_db]),
        ),
    ]
