# Generated by Django 6.0.1 on 2026-03-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_jugador_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color_carnet',
            field=models.CharField(default='#1D4ED8', help_text='Color en HEX para los carnets (Ej: #FF0000 para rojo, #00FF00 para verde)', max_length=7),
        ),
    ]
