# Generated by Django 6.0.1 on 2026-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_categoria_color_carnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='logo_sistema',
            field=models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Logo del Sistema'),
        ),
    ]
