# Generated by Django 6.0.1 on 2026-03-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_configuracion_logo_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='sanciones_aplicadas',
            field=models.BooleanField(default=False, verbose_name='¿Sanciones ya procesadas?'),
        ),
    ]
