# Generated by Django 6.0.1 on 2026-03-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_partido_sanciones_aplicadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonosancion',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_cobrados', to='core.partido'),
        ),
        migrations.AlterField(
            model_name='detallepartido',
            name='tipo',
            field=models.CharField(choices=[('GOL', '⚽ Gol'), ('ASIS', '✅ Asistencia'), ('TA', '🟨 Amarilla'), ('TR', '🟥 Roja'), ('DA', '🟨🟨 Doble A.'), ('AZUL', '👕 Uniforme'), ('EBRI', '🍺 Ebrio'), ('STAR', '⭐ Figura')], max_length=5),
        ),
    ]
