# Generated by Django 6.0.1 on 2026-03-30 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_abonosancion_partido_alter_detallepartido_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplejoDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Cancha / Complejo')),
                ('slug', models.SlugField(help_text='URL amigable, ej: cancha-los-pinos', unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para suspender la plataforma por falta de pago')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha máxima de cobertura del pago', null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='complejos/logos/')),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('organizador', models.OneToOneField(help_text='El dueño de este complejo', on_delete=django.db.models.deletion.CASCADE, related_name='complejo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Básico, Pro, Premium', max_length=50)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_torneos', models.IntegerField(help_text='Límite de torneos activos permitidos')),
                ('max_categorias_por_torneo', models.IntegerField(help_text='Límite de categorías por torneo')),
            ],
        ),
        migrations.DeleteModel(
            name='HorarioCancha',
        ),
        migrations.DeleteModel(
            name='Publicidad',
        ),
        migrations.RemoveField(
            model_name='reservacancha',
            name='cupon',
        ),
        migrations.RemoveField(
            model_name='reservacancha',
            name='partido',
        ),
        migrations.RemoveField(
            model_name='reservacancha',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='logo_sistema',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='precio_hora_cancha',
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='color_carnet',
            field=models.CharField(default='#1D4ED8', help_text='Color en HEX para los carnets', max_length=7),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de Categoría (Ej: Serie A, Femenino)'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='codigo',
            field=models.CharField(help_text='Ej: GOLAZO2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='partido',
            name='sanciones_aplicadas',
            field=models.BooleanField(default=False, verbose_name='¿Sanciones procesadas?'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='complejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.complejodeportivo'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='complejo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='core.complejodeportivo'),
        ),
        migrations.AddField(
            model_name='cupon',
            name='complejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to='core.complejodeportivo'),
        ),
        migrations.AddField(
            model_name='fotogaleria',
            name='complejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='core.complejodeportivo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='complejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.complejodeportivo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='complejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to='core.complejodeportivo'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('complejo', 'nombre'), name='unica_categoria_por_complejo'),
        ),
        migrations.AddConstraint(
            model_name='cupon',
            constraint=models.UniqueConstraint(fields=('complejo', 'codigo'), name='unico_cupon_por_complejo'),
        ),
        migrations.AddField(
            model_name='complejodeportivo',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plansuscripcion'),
        ),
        migrations.DeleteModel(
            name='ReservaCancha',
        ),
    ]
