# Generated by Django 6.0.1 on 2026-03-31 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_complejodeportivo_plansuscripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoSuscripcionSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto Pagado a NEXUS')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('meses_pagados', models.PositiveIntegerField(default=1, help_text='¿Cuántos meses pagó?')),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_saas', to='core.complejodeportivo')),
            ],
        ),
    ]
