# Generated by Django 6.0.1 on 2026-03-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pagosuscripcionsaas'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuscripcion',
            name='costo_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Costo de Inscripción (Pago único)'),
        ),
        migrations.AlterField(
            model_name='plansuscripcion',
            name='max_categorias_por_torneo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plansuscripcion',
            name='max_torneos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plansuscripcion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plansuscripcion',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
