# Generated by Django 6.0.1 on 2026-04-01 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_plansuscripcion_costo_inscripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='complejo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sancionado_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Suspendido (Lista Negra) Global hasta:'),
        ),
        migrations.CreateModel(
            name='RolComplejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ORG', 'Organizador / Staff'), ('VOC', 'Vocal de Mesa'), ('DIR', 'Dirigente de Equipo'), ('FAN', 'Aficionado / Cliente')], default='FAN', max_length=3)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.complejodeportivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_cancha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'complejo')},
            },
        ),
    ]
