# Generated by Django 6.0.1 on 2026-04-07 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_perfil_complejo_remove_perfil_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosuscripcionsaas',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha en que se realizó el pago'),
        ),
    ]
