# Generated by Django 6.0.1 on 2026-04-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_pagosuscripcionsaas_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='logo_sistema',
            field=models.ImageField(blank=True, null=True, upload_to='logos_sistema/', verbose_name='Logo Global de Nexus'),
        ),
    ]
