# Generated by Django 6.0.1 on 2026-08-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_pagosuscripcionsaas_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuscripcion',
            name='max_jugadores',
            field=models.PositiveIntegerField(default=50, help_text='Número total de jugadores que esta cancha puede tener registrados.', verbose_name='Máximo de jugadores inscritos'),
        ),
    ]
