# Generated by Django 6.0.1 on 2026-08-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_plansuscripcion_max_jugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='firma_local_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Local Base64'),
        ),
        migrations.AddField(
            model_name='partido',
            name='firma_visita_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Visita Base64'),
        ),
    ]
