# Generated by Django 6.0.1 on 2026-08-28 03:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_partido_firma_local_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(blank=True, help_text='Permite iniciar sesión con la cédula además del usuario.', max_length=10, null=True, unique=True, validators=[core.models.validar_cedula_db], verbose_name='Cédula'),
        ),
    ]
