# Generated by Django 6.0.1 on 2026-08-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20260827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='logo_sistema',
        ),
    ]
