# Generated by Django 6.0.1 on 2026-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_configuracion_logo_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='logo_sistema',
            field=models.ImageField(blank=True, help_text='Logo que se muestra en la barra de navegación, página de inicio, login y registro de todo el sistema.', null=True, upload_to='configuracion/logos/', verbose_name='Logo Global del Sistema'),
        ),
    ]
